### PR TITLE
STM32: fix HRTIM pwm init and corner case

### LINKED ISSUE #95: Analog output malfunction on AO2
It seems like AO2 pin is not correctly configured for PWM. There must be an issue in the AnalogOutClass section of the Arduino_MachineControl lib:
https://github.com/arduino-libraries/Arduino_MachineControl/blob/master/src/Arduino_MachineControl.h#:~:text=class%20AnalogOutClass%20%7B

The issue was discovered as follows: Even when AO2 is set to output 0V it always outputs 10V. I managed to replicate this result using the 'Analog_Out' sketch from Arduino_MachineControl library and configuring the Ao" as follows:

inside setup(): analog_out.period_ms(2, 4);
in loop(): analog_out.write(2, 0);

### PR DESCRIPTION
**Pull request by leonardocavagnis**
### Summary of changes 
Fixing HRTIM (High Resolution Timer) PWM initialization procedure that causes erroneous initialization of the duty cycle of the HRTIM channels in STM32 microcontrollers.

### Documentation 
None

----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [X] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [] Feature update (New feature / Functionality change / New API)
    [] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test results 

    [] No Tests required for this change (E.g docs only update)
    [] Covered by existing mbed-os tests (Greentea or Unittest)
    [X] Tests / results supplied as part of this PR
    
    
----------------------------------------------------------------------------------------------------------------
### Reviewers 

----------------------------------------------------------------------------------------------------------------

### CODE REVIEW

File: targets/TARGET_STM/pwmout_api.c [hunk 1]
```diff
@@ -142,9 +142,23 @@ static void _pwmout_init_direct(pwmout_t *obj, const PinMap *pinmap)
         pin_function(pinmap->pin, pinmap->function);
         pin_mode(pinmap->pin, PullNone);
 
-        obj->period = 0;
-        obj->pulse = 0;
-        obj->prescaler = 0;
+        // Initialize obj with default values (period 550Hz, duty 0%)
```
Comment (facchinm) [inline targets/TARGET_STM/pwmout_api.c:147]: This part is 1-to-1 the code in pwmout_period_us() function, can we simplify and only leave one :) ? Maybe via an helper function

**Review by facchinm — CHANGES_REQUESTED** [review]

File: targets/TARGET_STM/pwmout_api.c (hunk 1 above)
Comment (leonardocavagnis) [reply targets/TARGET_STM/pwmout_api.c:147]: Ok, I added an helper function 😉
